package com.leavemanagement.db.leavemanagement_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE LeaveBase PLEASE EDIT ../Leave.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Leave object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;

import org.springframework.jdbc.core.RowMapper;
import com.leavemanagement.db.leavemanagement_db.entity.Leave;

public class LeaveBase implements RowMapper<Leave>{
	
	private Long _id;
	
	// Attributes
    private Boolean cancel;
    private Date fromDate;
    private String reason;
    private String status;
    private Date toDate;
    private String type;
	
	
	
	@Override
	public Leave mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Leave obj = new Leave();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setCancel(rs.getBoolean("cancel"));
			obj.setFromDate(rs.getDate("fromDate"));
			obj.setReason(rs.getString("reason"));
			obj.setStatus(rs.getString("status"));
			obj.setToDate(rs.getDate("toDate"));
			obj.setType(rs.getString("type"));
			
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public Boolean getCancel() {
		return cancel;
	}


	public void setCancel(Boolean cancel) {
		this.cancel = cancel;
	}
	public Date getFromDate() {
		return fromDate;
	}


	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}
	public String getReason() {
		return reason;
	}


	public void setReason(String reason) {
		this.reason = reason;
	}
	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}
	public Date getToDate() {
		return toDate;
	}


	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}
	public String getType() {
		return type;
	}


	public void setType(String type) {
		this.type = type;
	}
	
    
    
    
    
}